parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - prettier
  - standard

extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/standard
  - prettier/@typescript-eslint
